#!/usr/bin/perl -l -s --

sub do_main()
{
	if($g == 3 || !defined($g)){
	}elsif($g == 2){
		my @k;
		my @s = (0,0);

		if(length($_) < 8){
			$_ = pack("A8",$_);
		}

		my $j = 8 / length($_);
		for(my $i = 0; $#k < 7; ++$i){
			if($#k + 1 < int($j * $i)){
				push(@k,substr($_,$i - 1,1));
			}
		}

		if(defined($seed)){
			push(@s,$seed);
		}elsif(length($ENV{SEED})){
			push(@s,$ENV{SEED});
		}elsif(length($ENV{HOSTNAME})){
			push(@s,$ENV{HOSTNAME});
		}
		for(my $i = 0; $i < length($s[2]); ++$i){
			$s[$i & 1] += ord(substr($s[2],$i,1));
		}
		$s[0] = (0..9,a..z,A..Z,qw(+ /))[$s[0] % 64];
		$s[1] = (0..9,a..z,A..Z,qw(+ /))[$s[1] % 64];

		$_ = substr(crypt(join(undef,@k),join(undef,@s[0,1])),-10);
	}elsif($g == 1){
		my @k;

		if(length($_) < 8){
			$_ = pack("A8",$_);
		}

		my $j = 8 / length($_);
		for(my $i = 0; $#k < 7; ++$i){
			if($#k + 1 < int($j * $i)){
				push(@k,substr($_,$i - 1,1));
			}
		}

		$_ = substr(crypt(join(undef,@k),$k[0].$k[7]),-10);
	}else{
		$_ = sprintf("E%d Unknown generating option %s. : -g=<1,2,3>",__LINE__,$g);
	}
	print;
}

if($#ARGV == -1){
	while(<STDIN>){
		chomp();
		do_main();
	}
}else{
	foreach(@ARGV){
		do_main();
	}
}

0
